# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\plugin\builtin\fastFourierTranformation\ui\fft.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 500)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FFTPlaceholder = QtWidgets.QLabel(Form)
        self.FFTPlaceholder.setText("")
        self.FFTPlaceholder.setObjectName("FFTPlaceholder")
        self.horizontalLayout_2.addWidget(self.FFTPlaceholder)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
